name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Setup Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      # Add Rust targets for cross-compilation (macOS only)
      - name: Add macOS targets
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
      
      # Install platform-specific dependencies
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      
      # Install Tauri CLI
      - name: Install Tauri CLI
        run: cargo install tauri-cli
      
      # Build the app
      - name: Build the app
        run: npm run tauri build
      
      # Upload Windows artifacts
      - name: Upload Windows artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: notter-windows
          path: src-tauri/target/release/bundle/msi/*.msi
          if-no-files-found: error
      
      # Upload macOS artifacts
      - name: Upload macOS artifacts
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: notter-macos
          path: src-tauri/target/release/bundle/dmg/*.dmg
          if-no-files-found: error
      
      # Upload Linux artifacts
      - name: Upload Linux artifacts
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: notter-linux
          path: src-tauri/target/release/bundle/appimage/*.AppImage
          if-no-files-found: error
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Download all artifacts
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: notter-windows
          path: artifacts/windows
      
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: notter-macos
          path: artifacts/macos
      
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: notter-linux
          path: artifacts/linux
      
      # Extract version from tag
      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      # Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Notter v${{ steps.extract_version.outputs.VERSION }}
          files: |
            artifacts/windows/*.msi
            artifacts/macos/*.dmg
            artifacts/linux/*.AppImage
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
